-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Aihe CASCADE;
DROP TABLE IF EXISTS Aihealue CASCADE;
DROP TABLE IF EXISTS Vastaus CASCADE;
DROP TABLE IF EXISTS KayttajaRyhma CASCADE;
DROP TABLE IF EXISTS Luettu CASCADE;
DROP TABLE IF EXISTS KayttajaKuuluu CASCADE;
DROP TABLE IF EXISTS AihealueKuuluu CASCADE;